### PR TITLE
Don't update display_name to empty string

### PR DESCRIPTION
**Pull request by pacmessica**
[notion](https://www.notion.so/figmentnetworks/b47c0f8b935741d8ac28717ddeea2038?v=5e4e1d3854094b788ae2b612329f27e8&p=5f5352157bee458698749e63ba6f5c35)

Issue is that we update validator aggs based on `ParsedValidatorsData`. `ParsedValidatorsData` is comprised of `rawStakingState.GetValidators()` (where display name is) and `rawValidatorPerformances` and it's possible for there to be values in the latter and not the former. When that's the case, the we don't want to update the display_name since there is no value.

### CODE REVIEW

**Comment by pawelnguyen** [comment]
you mentioned 22 validator names in Notion, looking at Polkascan it seems right https://polkascan.io/polkadot/account/validators

**Review by silentlight — APPROVED** [review]
Nice! Does it mean that we have to run backfill?

**Comment by pacmessica** [comment]
> Nice! Does it mean that we have to run backfill?

yeah, that's true! I'll update the config.

however is it worth running the backfill for this one thing? All the validators at the top of the chain will be up to date without backfill, so only a handful of older validators that stopped running are effected by this. Given how rare names are, I suspect this is a very small number of names that we're missing. Since we're still actively developing polkadot, I think it's ok to wait because we'll probably have to backfill for milestone 3 tasks anyway. What do you think @silentlight?

I just remember backfill taking sooo long. Maybe it's worth optimizing the backfill process to add a flag so that it only fetches end_of_era/end_of_session heights when we know the data only exists at those heights (eg for validators)

**Comment by pawelnguyen** [comment]
I also think that we can do a backfill in a week or more from now

**Comment by silentlight** [comment]
Yeah I agree no need to do backfill just yet. I think you are right @pacmessica . We could connect validator data to only backfill at certain heights (end of session and end of era). This might be a good task for @eesmerdag. What do you think?

**Comment by pacmessica** [comment]
> Yeah I agree no need to do backfill just yet. I think you are right @pacmessica . We could connect validator data to only backfill at certain heights (end of session and end of era). This might be a good task for @eesmerdag. What do you think?

sounds like an excellent task for emir 😸

**Comment by eesmerdag** [comment]
> > Yeah I agree no need to do backfill just yet. I think you are right @pacmessica . We could connect validator data to only backfill at certain heights (end of session and end of era). This might be a good task for @eesmerdag. What do you think?
> 
> sounds like an excellent task for emir 😸

Sure :handshake:

**Pull request merged**
